Add block via RPC prior to successful block application
koinos/koinos-chain pull request #385
Opened 2021-04-27 01:40 UTC by sgerbino

Resolves #382.

2021-04-27 07:04 UTC, sgerbino commented
Blocked by koinos/koinos-exception-cpp#1

2021-04-27 16:04 UTC, mvandeberg approved these changes

2021-04-27 23:02 UTC, mvandeberg requested changes

2021-04-27 23:02 UTC, mvandeberg commented on libraries/chain/controller.cpp
> +               throw koinos::exception( "Unexpected response from block store" );
Let's use `KOINOS_THROW` to get the stack trace correctly.

2021-05-11 20:04 UTC, mvandeberg approved these changes

2021-05-11 20:04 UTC, merged