Implement capsule library (tree_walker and unit tests)
koinos/koinos-chain pull request #392
Opened 2021-05-17 21:30 UTC by theoreticalbts

2021-05-26 01:25 UTC, theoreticalbts commented
Fixed clang compilation errors, ready for review.

2021-05-26 20:58 UTC, sgerbino requested changes

2021-05-26 20:58 UTC, sgerbino commented on libraries/capsule/include/koinos/capsule/capsule.hpp
> +            int64_t height = boost::multiprecision::detail::find_msb(leaf_id);
Applications should not be using `detail::` from boost.

2021-05-26 20:58 UTC, sgerbino commented on tests/tests/capsule_test.cpp
> +   std::vector< std::tuple< int64_t, std::vector< int64_t >, std::string > > cases = {
We should avoid using nested vectors of magic numbers, it makes the test cases hard to understand and maintain.

2022-01-18 21:37 UTC, mvandeberg commented
Pull is closed due to age

2022-01-18 21:37 UTC, closed without merging